=== JuanDaw/1daw/lmsgi/2trim/tema4/examen/catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="catalogo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element  name="autor" type="xs:string" />
              <xs:element name="titulo" type="xs:string" />
              <xs:element name="genero">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Informatica"/>
                    <xs:enumeration value="Fantasia"/>
                    <xs:enumeration value="Historia"/>
                    <xs:enumeration value="Literatura"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="precio">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="5" />
                    <xs:maxInclusive value="100" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="fechaPublicacion">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="descripcion">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="100" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:all>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JuanDaw/1daw/lmsgi/2trim/tema4/examen/catalogo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo
xmlns:xs= "http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="catalogo.xsd">
  <libro id="bk101">
    <autor>Garghentini, Davide</autor>
    <titulo>Guía de desarrollo XML</titulo>
    <genero>Informatica</genero>
    <precio>44.95</precio>
    <fechaPublicacion>01-01-2000</fechaPublicacion>
    <descripcion>Una revisión profunda a la creación de aplicaciones con XML</descripcion>
  </libro>
  <libro id="bk102">
    <autor>García, Debra</autor>
    <titulo>Lluvia de medianoche</titulo>
    <genero>Fantasia</genero>
    <precio>5.95</precio>
    <fechaPublicacion>16-12-2000</fechaPublicacion>
    <descripcion>Un antiguo arquitecto lucha contra zombis corporativos,
    una hechicera, y su propia infancia.</descripcion>
  </libro>
</catalogo>
