=== JuanDaw/1daw/lmsgi/2trim/tema4/examen/catalogo.dtd
<!ELEMENT catalogo (libro+)>
<!ELEMENT libro (autor, titulo, genero, precio, fechaPublicacion, descripcion)>
<!ATTLIST libro
          id CDATA #REQUIRED>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== JuanDaw/1daw/lmsgi/2trim/tema4/examen/catalogo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
  <libro id="bk101">
    <autor>Garghentini, Davide</autor>
    <titulo>Guía de desarrollo XML</titulo>
    <genero>Informática</genero>
    <precio>44.95</precio>
    <fechaPublicacion>01-01-2000</fechaPublicacion>
    <descripcion>Una revisión profunda a la creación de aplicaciones con XML</descripcion>
  </libro>
  <libro id="bk102">
    <autor>García, Debra</autor>
    <titulo>Lluvia de medianoche</titulo>
    <genero>Fantasia</genero>
    <precio>5.95</precio>
    <fechaPublicacion>2000-12-16</fechaPublicacion>
    <descripcion>Un antiguo arquitecto lucha contra zombis corporativos,
    una hechicera malvada, y su propia infancia para convertirse en rey del mundo.</descripcion>
  </libro>
</catalogo>
